### ISSUE TITLE
"uninitialized constant Aws" error in version 2.6.0

### ISSUE THREAD

**Issue by serebrov** [chef-cookbooks/aws#104]
Today our deployment start failing and the reason seems to be the recently released 2.6.0 version.
The error in aws opsworks log is this:

```
================================================================================
Error executing action `update` on resource 'aws_resource_tag[i-540be0b9]'
================================================================================
 
 
NameError
---------
uninitialized constant Aws
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/aws/libraries/ec2.rb:43:in `ec2'
/var/lib/aws/opsworks/cache.stage2/cookbooks/aws/providers/resource_tag.rb:89:in `load_current_resource'
```
I see the recent change in the [line](https://github.com/opscode-cookbooks/aws/commit/757ddaa3ad83d35a87e49c625baa6c2dede44c00#diff-7be4cd6ebd09c170768d51983b8c7d44L43) mentioned in the error text.

Reverting to version 2.5.0 fixed the issue with our deployment.

Update:

Just for the case here is a custom recipe code:
```ruby
include_recipe "aws"
tags_data = {
  "MakeSnapshot" => "True"
}
aws_resource_tag node['ec2']['instance_id'] do
    tags(tags_data)
    action :update
end
```

**Comment by thanhn08** [comment]
I am having the same problem. After looking at the code, I think the main reason is "aws-sdk".
It seems that my instances on AWS already had "aws-sdk" installed and its version was 1.x.x. This AWS cookbook requires "aws-sdk" 2.x.x so it doesn't work. 

In aws-sdk version 1.x.x, the module was named "AWS" instead of "Aws" like in version 2.x.x.

How can I revert the AWS cookbook back to 2.5.0? I set it default using "include_recipe" in the recipe files and "depends" in metadata.

Thanks.

**Comment by serebrov** [comment]
@thanhn08 I reverted it to the previous version via Berksfile:

```
source 'https://supermarket.getchef.com'

cookbook 'mongodb'
cookbook 'aws', '= 2.5.0'
```

See the '= 2.5.0' for aws cookbook.

**Comment by davidski** [comment]
I was bit by this as well (go figure, the one dependency I didn't have well pinned is the one that bites me). There is a blog post from the AWS team talking about this error at http://ruby.awsblog.com/post/TxFKSK2QJE6RPZ/Upcoming-Stable-Release-of-AWS-SDK-for-Ruby-Version-2.

**Comment by Scythril** [comment]
@davidski I don't think this particular error is related to the article you linked. The article mentions AWS is uninitialized, while the OP's error has Aws (note the case). That's because they used AWS in v1 of the sdk, and then changed to Aws in v2 (which is the version this cookbook is now using). Still, it's good info.

**Comment by zanzan42** [comment]
Same problem here. I'm reverting to explicitly set =2.5.0 in my berksfile, but I'm bummed because I'm specifically waiting for the S3 IAM role support which is rolled into 2.6.0.

**Comment by Scythril** [comment]
Are you guys running the default recipe first? ```include_recipe "aws"```

If not, you should; it would take care of installing the `aws-sdk` gem for you.

If you are, are you setting an explicit `node['aws']['aws_sdk_version']`?

This cookbook shouldn't be colliding with v1 of the `aws-sdk` since the v 2.5.0 is using `right_aws`, not `aws-sdk-v1`, unless `node['aws']['aws_sdk_version']` is being set to v1. I may be missing something else, just trying to help. It works for me for what it's worth.

**Comment by zanzan42** [comment]
Yes, I have include_recipe "aws". This all works fine with 2.5.0 (and I'm only using it to get something from S3, which under 2.5.0 using right_aws), but breaks immediately with 2.6.0 (which swaps in using aws-sdk for the S3 functionality). I am not setting the aws_sdk_version, although I might try testing that by overriding the value on my OpsWorks stack to see if explicitly setting it to version 1 works.

**Comment by Scythril** [comment]
It won't; v1 of the sdk isn't backwards-compatible, and from what I've seen in the diff here between v2.5 and v2.6, it wasn't written to be compatible with v1 of the `aws-sdk`. The default attribute in this cookbook already sets it to `'~> 2.0.22'`, so you should be good there.

**Comment by davidski** [comment]
@Scythril The default attribute works well for installing V2 of the `aws-sdk` but doesn't do anything for when the `require` statement loads the gem. I've not validated this, but I strongly suspect that for OpsWorks users (like most of us experiencing this error seem to be), we're getting `aws-sdk` V1 from somewhere (either an OpsWorks recipe or our default AMIs) which the `aws` recipe is loading since the `require` statement doesn't call out which version it wants.

This would seem to trigger the AWS/Aws issue since the V2 is looking for `Aws` and is finding only `AWS` from the loaded V1 gem, even though V2 is likely installed as well.

**Comment by zanzan42** [comment]
I can verify that the V2 version of the gem gets installed, because I see that when I run "update dependencies" in OpsWorks. Yet it still fails running my recipe because it can't find Aws. Per the documentation, there are some steps you (the author of the aws recipe) would have to take to make sure the right require is in place (sorry about the loss of formatting here):

Lock your Dependencies

The V2 Ruby SDK is not backwards compatible with the V1 Ruby SDK. If you have a bundler dependency on aws-sdk and you do not specify a version, you will run into problems with the 2.0 final is released. To ensure you are unaffected by the major version bump, ensure you specify a version dependency in your Gemfile:

?
1
gem 'aws-sdk', '< 2.0'
Alternatively, you can change your gem dependency from aws-sdk to aws-sdk-v1

?
1
gem 'aws-sdk-v1'
The AWS SDK for Ruby follows semver. This allows users to update within the same major version with confidence that there are not backwards incompatible changes. If there are, they will be treated as bugs.

Use Both Version in One Application

The V1 and V2 Ruby SDKs use different namespaces. You may only load one version of a single gem. We publish the v1 Ruby SDK as a separate gem now to allow users to load both versions. Additionally, the v2 SDK uses a different root namespace to avoid conflicts.

?
1
2
3
# in your Gemfile
gem 'aws-sdk-v1'
gem 'aws-sdk', '2.0.0.pre'
And then in your application:

?
1
2
3
4
5
6
require 'aws-sdk-v1'
require 'aws-sdk'
 
# v1 uses the AWS module, v2 uses the Aws module
s3_v1 = AWS::S3::Client.new
s3_v2 = Aws::S3::Client.new

**Comment by zanzan42** [comment]
Any update on this?

**Comment by ubiquitousthey** [comment]
As far as I know, bundler is not used with chef-client.  The chef_gem should install the aws-sdk gem in the gem path for chef-client.  If you have another recipe that is installing the aws-sdk-v1 using the same method there could definitely be a conflict.  

I am not that familiar with opsworks.  In an omnibus install it would be under /opt/chef/embedded/lib/ruby

**Comment by zanzan42** [comment]
As has been mentioned, both the v1 and v2 gems are present, but it is up to the recipe to dictate which one it is actually going to use, and it seems like that is the part that is failing.

**Comment by zanzan42** [comment]
Per the aws-sdk README, there needs to be an explicit call somewhere in your recipe to use V2:

http://docs.aws.amazon.com/sdkforruby/api/index.html

"
Installation
The AWS SDK for Ruby is available as the aws-sdk gem from RubyGems. Please use a major version when expressing a dependency on aws-sdk.

gem 'aws-sdk', '~> 2'
"

Also per the docs, both V1 and V2 gems can co-exist, but, again, your app has to be explicit about when it's using v1 vs. V2:

"
NameError: uninitialized constant AWS
If you receive this error, you likely have upgraded to version 2 of the aws-sdk gem unintentionally. Version 2 uses the Aws namespace, not AWS. This allows version 1 and version 2 to be used in the same application.

See this blog post for more information: http://ruby.awsblog.com/post/TxFKSK2QJE6RPZ/Upcoming-Stable-Release-of-AWS-SDK-for-Ruby-Version-2
"

**Comment by ubiquitousthey** [comment]
I do not claim to be either a rubygems or chef expert, but there is no Gemfile for chef recipes, and bundler is not used.  The chef_gem resource in the default recipe is explicitly installing V2 as the gem call would.  

As you notice in the documentation you copied in, it is the V1 references that must specify the version in the ruby code.  I think it is the recipe using the V1 gem that will have to change to install the aws-sdk-v1 gem and use the require aws-sdk-v1 statement to import the aws-sdk-v1 library.  There is no aws-sdk-v2 gem, it is just aws-sdk.

I am happy for someone who knows to correct me and submit a PR.  Otherwise, I suggest you use the previous version or update the other recipe to use V2 or use the 'was-sdk-v1' gem.

**Comment by mausch** [comment]
I'm getting "uninitialized constant Aws" (*not* uppercase, so no 1.x) as well, even when downgrading to 2.5.0 . Is there a stable version or something like that I should be using?

**Comment by Scythril** [comment]
@mausch Did you remember to run/include the default recipe in this cookbook first?

**Comment by mausch** [comment]
@Scythril  Never mind, it seems that IAM role support for S3 is still an open issue ( https://github.com/opscode-cookbooks/aws/issues/71 ) so I removed the cookbook and instead I'm writing a ruby_block using aws-sdk directly. Which still gives me "uninitialized constant Aws" but at least it's not related to this project I guess :-)
Cheers

**Comment by ubiquitousthey** [comment]
IAM role credentials are supported for S3 since 2.6.0.

**Comment by mausch** [comment]
@ubiquitousthey Cool, thanks. I wonder why #71 is still open though.
As a newbie in Chef I'm probably doing something really stupid, and since I'm not getting any helpful errors and `knife` doesn't work either I'm left with the worst kind of programming there is: trial-and-error. Googling the error I landed here, I tried the suggestion at the top to downgrade to 2.5.0, still getting the same error. No idea what to do next, I guess I'll keep trying things until something sticks. Quite frustrating.

**Comment by electronym** [comment]
@mausch I'm having the same issues as you are (aws cookbook as well as using a ruby block fail if I try to use v2 of the sdk - same message about uninitialized constant Aws despite it definitely being installed). Reverting to v1 and doing it manually is the only way I've gotten this to work, so if you manage to solve this I'd love to hear how.

**Comment by mausch** [comment]
@electronym Thanks, downgrading to v1 worked for me as well. I've filed a support ticket with Amazon about this.

**Comment by mapoulin** [comment]
I faced this issue with version 2.7.0. Downgrading worked for me as well.

@mausch Any update following the support ticket ?

**Comment by zanzan42** [comment]
You might try this cookbook instead. It has included S3 IAM role recognition for some time (since January), but they didn't update it with owner/group/mode on the file laydown until today (at my request). It should now do everything I've been looking for in regard to pulling a file from S3 and depositing it on my instances, using IAM roles instead of API keys.

https://github.com/awslabs/awscli-cookbook

**Comment by mausch** [comment]
I got this reply from Amazon a few weeks ago:

> V1 will not be changed and 'aws-sdk' still uses v1.   We're just simply moving 'aws-sdk' to v2 rather than keeping it v1.  So v1 will not be touched and v2 will be declared as "aws-sdk"

I guess what they meant is "V1 will not be changed and 'aws-sdk-v1' still uses v1". I haven't tried changing my recipe yet.

**Comment by rgokhale** [comment]
I have run into the exact same issue with the latest version 2.7.2. Downgrading to 2.5.0 works fine for me, but I need to use the aws_ebs_volume and encrypt the volumes, encryption wasn't added until version 2.7.0. @mausch have you had any luck making this work?

**Comment by ferdy-lw** [comment]
I think this is a problem with the opsworks agent depending on the v1 aws-sdk. It appears to use aws-sdk 1.53.0 (`/opt/aws/opsworks/current/Gemfile.lock`), and as per https://github.com/aws/opsworks-cookbooks/issues/85#issuecomment-30128614 it looks like you can't simply chef_gem a newer version.

I see the aws-sdk 2.0.48 being installed, but still end up with this error.

Does anyone know how to force, or require a newer gem in the recipe - otherwise this aws cookbook now doesn't work on opsworks clients?

**Comment by mausch** [comment]
I was using this as part of a deployment but I've since switched to Docker so I no longer need it.

**Comment by punnie** [comment]
any development on this?

**Comment by miketheman** [comment]
Cookbook version 2.7.2 uses the correct aws-sdk gem, and also the correct namespace.

I think we need a clearer, concise bug report as to how this is being called on the latest version of the cookbook before considering further action here.

Thanks to everyone who's reported up until now, but there's been so much change since 2.5.0 and 2.7.2, I cannot wade through it all right now.

**Comment by ebeyrent** [comment]
FWIW, I tried to use version 2.7.2 and ran into the exact same issue, which was resolved by downgrading to 2.5.0.

**Comment by habelson** [comment]
I am running into the same problem. I can't use 2.7.2 because the correct version of the aws_sdk gem doesn't appear to be loaded correctly on OpsWorks, and I also can't use 2.5.0 because I need IAM support for S3. So I'm stuck with very few options?

**Comment by zanzan42** [comment]
If all you need is the S3 functionality, just use s3_file (which started being included as part of the base opsworks cookbook set a couple months ago, and supports IAM roles).

**Comment by mathomas** [comment]
@zanzan42 Thanks for the reference to s3_file!  That was a 20-minute lifesaver after wasting hours trying to get the AWS cookbook working for an S3 copy under OpsWorks.

**Comment by zanzan42** [comment]
No problem.

**Comment by kenwdelong** [comment]
I have this in my Berksfile:  `cookbook 'aws', '>= 2.5.0'`

I have this in the cookbook's metadata.rb: `depends 'aws'`

I have this in my cookbook's recipes/default.rb:

```
include_recipe "aws"

# Create tags
unless node['hatch']['tags'].empty? || node['hatch']['tags'].nil?
    aws_resource_tag node['ec2']['instance_id'] do
        tags(node['hatch']['tags'])
        action :update
    end
end
```

It fails.

This is in my failed setup log:
`Installing aws (2.9.2)`
and
```NameError
---------
uninitialized constant Aws
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/aws/libraries/ec2.rb:49:in `ec2'
/var/lib/aws/opsworks/cache.stage2/cookbooks/aws/providers/resource_tag.rb:88:in `load_current_resource'
 
 
Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/hb-common/recipes/default.rb
 
31:     aws_resource_tag node['ec2']['instance_id'] do
32:         tags(node['hatch']['tags'])
33:         action :update
34:     end
35: end
```

@miketheman I hope this report is clear enough.

For now, I am downgrading to 2.5.0.

**Comment by tas50** [comment]
I believe these errors have been resolved in the 3.X series of the cookbook.  We're handling the gem install and gem loading much better now.  Give it a try and let me know if it's still an issue.

**Comment by zachlowry** [comment]
Just tried this with 3.3.2 and it's still an issue on OpsWorks.

**Comment by zachlowry** [comment]
Is it possible to re-open this @tas50? I'm not sure that there's anything that can be done on your end, but it still causing all sorts of problems for us.

**Comment by zanzan42** [comment]
This is still a problem (and I commented on Issue 181, which is related to this one) a few minutes ago. Since the longer/more detailed conversation is on this issue thread, I'll put it here instead:

This is still a problem for OpsWorks recipes which use aws as a dependency. While I punted and use a different s3_file cookbook (which has been included in the OpsWorks base set since about November), tagging recipes which depend on aws still continue to fail with the uninitialized constant Aws error.

For instance, this one:

https://github.com/stuart-warren/chef-aws-tag
