### ISSUE TITLE
aws_s3_file doesn't do conditional requests

### ISSUE THREAD

**Issue by kingpong** [chef-cookbooks/aws#169]
I am seeing aws_s3_file re-download S3 resources even when the resource hasn't changed. It looks like the s3_file provider [signs the URL](https://github.com/opscode-cookbooks/aws/blob/master/providers/s3_file.rb#L34) and then hands it off to remote_file. Since the signed URL is different each time, the [CacheControlData key](https://github.com/chef/chef/blob/d8172e646d9fbf43e57bca5e20d0ac352ba9a66a/lib/chef/provider/remote_file/cache_control_data.rb#L151) where the request metadata is stored will necessarily change on each Chef run.

**Comment by muddman** [comment]
+1

**Comment by jkburges** [comment]
:+1:

FWIW, https://github.com/adamsb6/s3_file *does* appear to implicitly handle conditional downloads (i.e. it won't re-download if the object hasn't changed).

**Comment by tas50** [comment]
The latest 3.X release now checks the files before trying to download them again.  Give it a try and let me know if that resolves this for you.

**Comment by jkburges** [comment]
Thanks @tas50.  I don't work on the project where I wanted this functionality any more, but @danfruehauf might be interested.  This would enable the dependency on  https://github.com/adamsb6/s3_file to be removed (and use this cookbook instead).

**Comment by jkburges** [comment]
Turns out I do still have some chef code which fetches things from S3.  I just tried this and it works :-)

One thing I noticed though is that sometimes the `etag` in S3 is *not* the MD5 hash, so perhaps this code should be doing an HTTP conditional GET, rather than basing the decision on MD5 of cached file?  This would still be relatively fast if the file has not changed.

It looks as though the underlying resource [remote_file](https://docs.chef.io/resource_remote_file.html) supports conditional GET based on `etag`.

**Comment by jkburges** [comment]
Looks like the change is using etag, but it never gets that far because [compare_md5s](https://github.com/inhumantsar/aws/commit/dc8d7fb87536f369dab9eb56e994ddf624f4cd3b#diff-c65647e990f88b6c518d9faf67a612b5R17) is causing (sometimes incorrectly) the action to be skipped.

**Comment by joelvanvelden** [comment]
This issue is still happening. There are a number of bad assumptions in this logic.

1. If the object in S3 is uploaded as multipart ([aws cli default threshold is 8MB](http://docs.aws.amazon.com/cli/latest/topic/s3-config.html#multipart-threshold) so this is quite a common case)
1. On the second chef run, compare_md5s() will always fail:
  * It re-calculates the md5 of the local file (which not a great idea as files aren't always small)
  * It fetches the objects etag from s3
  * Checks if they are the same, which is not correct as the etag is not a md5hash.
1. Passes the signed url to remote_file which consults its cache to get last-modified/etag to send with http request, but metadata cache lookup fails due to using presigned url which is always changing, which results in always re-downloading the entire object.

This is causing my client a number of issues.

Where to go from here? It would seem that either:

1. Don't use pre-signed url's and instead bypass remote_file to do our own downloading and caching.
  * Allows using the ruby s3 sdk to download which likely handles failures/edge cases better
  * Avoids pre-signed urls which can cause interesting permissions issues.

1. Somehow massage remote_file to store its metadata cache with a different key
  * Likely would require a lot more work


I'd advocate for option 1 myself.
