### ISSUE TITLE
missing require for aws-sdk?

### ISSUE THREAD

**Issue by shortdudey123** [chef-cookbooks/aws#181]
When using the `aws_s3_file` LWRP, I get an error saying `uninitialized constant Aws`.  Looks like this is because stuff from the `Aws` namespace is [used](https://github.com/chef-cookbooks/aws/blob/master/libraries/s3.rb#L9) before the gem is [required](https://github.com/chef-cookbooks/aws/blob/master/libraries/ec2.rb#L60).

Anyone else seeing this? If so, I can put in a PR

```
Recipe: XXXXX::XXXXX
  * aws_s3_file[/var/chef/cache/XXXXX] action create
    
    ================================================================================
    Error executing action `create` on resource 'aws_s3_file[/var/chef/cache/XXXXX]'
    ================================================================================
    
    NameError
    ---------
    uninitialized constant Aws
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/aws/providers/s3_file.rb:33:in `do_s3_file'
    /var/chef/cache/cookbooks/aws/providers/s3_file.rb:9:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/XXXXX/recipes/XXXXX.rb
    
     25: aws_s3_file "#{Chef::Config[:file_cache_path]}/#{filename}" do
     26:   bucket 'XXXXX'
     27:   remote_path "XXXXX/#{filename}"
     28:   aws_secret_access_key bag['aws_secret_key']
     29:   aws_access_key_id bag['aws_access_key']
     30:   not_if { ::File.exist?("#{Chef::Config[:file_cache_path]}/#{filename}") }
     31: end
     32: 

```

Gem versions
```
$ gem list | grep aws
aws-sdk (2.1.33)
aws-sdk-core (2.1.33)
aws-sdk-resources (2.1.33)
aws-sdk-v1 (1.66.0)
$
$ /opt/chef/embedded/bin/gem list | grep aws
aws-sdk (2.0.48)
aws-sdk-core (2.0.48)
aws-sdk-resources (2.0.48)
$
```

**Comment by zanzan42** [comment]
Yes. This has been a problem for anybody using OpsWorks ever since Amazon went to the new version of aws-sdk. I haven't been using this cookbook (or any dependent on it) ever since that happened, due to the uninitialized constant error. Been using the awscli cookbook from awslabs for S3 gets instead.

However, there is another cookbook for tagging OpsWorks instances that I'd like to use, and it's dependent on the ec2 tagging LWRP in this cookbook as well (which has the same problem). So if the issue can be fixed, I'm all for it.

**Comment by shortdudey123** [comment]
@zanzan42 glad i am not the only one haha
I will put a PR in for this

**Comment by doitagain** [comment]
I'm experiencing the same issue using aws-sdk 2.2.0.  

> aws-sdk (2.2.0)
> aws-sdk-core (2.2.0)
> aws-sdk-resources (2.2.0)

Is there a workaround that can be used for the short term?

**Comment by shortdudey123** [comment]
@doitagain see the PR above

**Comment by doitagain** [comment]
@shortdudey123 thanks for responding so quickly.  I see the PR, but I'm new to chef and don't understand how to reference that branch in my Berksfile or metadata.rb.  If you have time, would you mind providing an example?  

This is what I've tried:

Berksfile
> cookbook 'aws', branch: 'add_needed_gem_require'

metadata.rb
> depends 'aws'

**Comment by shortdudey123** [comment]
look at the `Git Location` section of http://berkshelf.com/v2.0/

**Comment by doitagain** [comment]
Clear now... thank you!

**Comment by felix-okta** [comment]
+1

**Comment by doitagain** [comment]
I've tested the above but keep get the same error.  What is the last known stable version for s3 file?  2.7.2 seems unusable.

**Comment by shortdudey123** [comment]
@doitagain error output?

**Comment by tas50** [comment]
I think this is part of a larger problem where we shouldn't require the aws::default recipe in order to install / load the SDK gem.  Instead we should dynamically install the gem when needed and require the sdk as needed.  The fix in #183 partially fixes it, but as @miketheman pointed out the real fix is more complex and should probably be done.  I'm still a bit partial to getting the mini-fix in place now, but I'm going to look into what it will take to refactor things the right way.

**Comment by shortdudey123** [comment]
@tas50 Thanks!

**Comment by doitagain** [comment]
@shortdudey123 my error output is the same that you reported. 

```
================================================================================
Error executing action `create` on resource 'aws_s3_file[/usr/local/jdk1.8.0_65.tar.gz]'
================================================================================

 
NameError
---------
uninitialized constant Aws
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/aws/providers/s3_file.rb:34:in `do_s3_file'
/var/lib/aws/opsworks/cache.stage2/cookbooks/aws/providers/s3_file.rb:10:in `block in class_from_file'
```

**Comment by doitagain** [comment]
I apologize for being so confused over usage of s3_file.  I've read through the docs, the above PR, this issue, and the OpsWorks docs repeatedly and can't figure out how to add the aws recipe to the run_list on OpsWorks.  I've tried executing aws::default directly and still result in the "uninitialized constant Aws" error.

I realize this may be out of scope, but clarification on use of the aws cookbook on OpsWorks would be greatly appreciated.

**Comment by mmamane** [comment]
@doitagain downgrade to 2.5.0.  There seems to be too much confusion over the use of anything more recent.

**Comment by tas50** [comment]
We have a fix on master for this.  It'll go out with the next release.

**Comment by zanzan42** [comment]
This is still a problem for OpsWorks recipes which use aws as a dependency. While I punted and use a different s3_file cookbook (which has been included in the OpsWorks base set since about November), tagging recipes which depend on aws still continue to fail with the uninitialized constant Aws error.

For instance, this one:

https://github.com/stuart-warren/chef-aws-tag
