### ISSUE TITLE
ELB in VPC is not supported in this version of API

### ISSUE THREAD

**Issue by jslusher** [chef-cookbooks/aws#79]
I'm trying to add instances to an ELB, but it doesn't seem to work in a VPC.

      ================================================================================
    Error executing action `register` on resource 'aws_elastic_lb[test-mysql]'
================================================================================

    RightAws::AwsError
------------------
    ValidationError: ELB in VPC is not supported in this version of API. Please try 2011-11-15 or newer.

**Comment by Scythril** [comment]
Just wanted to give you all an update here, since v2.6.0 of the aws cookbook, it is now using the aws-sdk gem, which does support ELBs in a VPC. I had written my own snippet to allow me to do this, but now that they're using the aws-sdk gem, I pulled out my version, and it works with the `aws_elastic_lb` provider.

**Comment by tas50** [comment]
This should be resolved as we cutover to the official AWS gem.
